name: wakku_minjok
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  package_rename: ^1.9.0
  flutter_flavorizr: ^2.3.0
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  riverpod_generator: ^2.6.5
  retrofit_generator: ^9.1.9
  retrofit: ^4.4.2
  go_router: ^14.8.1
  go_router_builder: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  
# flutter pub run flutter_flavorizr
flavorizr:
  ide: vscode
  app:
    android:
      flavorDimensions: flavor-type
  flavors:
    dev:
      app:
        name: 와꾸의 민족 dev
      android:
        applicationId: com.wakku.minjok.dev
        # icon: assets/icons/dev/app_icon_dev.png
      ios:
        bundleId: com.wakku.minjok.dev
        # icon: assets/icons/dev/app_icon_dev.png
    prod:
      app:
        name: 와꾸의 민족
      android:
        applicationId: com.wakku.minjok
        # icon: assets/icons/prod/app_icon_prod.png
      ios:
        bundleId: com.wakku.minjok
        # icon: assets/icons/prod/app_icon_prod.png
